package com.ks.logic.service;

import com.ks.logic.dao.AgainstRequstDAO;
import com.ks.logic.dao.AreaConfigDAO;
import com.ks.logic.dao.ArenaDAO;
import com.ks.logic.dao.ExploreDAO;
import com.ks.logic.dao.FightDAO;
import com.ks.logic.dao.FriendDAO;
import com.ks.logic.dao.GameLoggerDAO;
import com.ks.logic.dao.GuildAccuseDAO;
import com.ks.logic.dao.GuildApplyDAO;
import com.ks.logic.dao.GuildDAO;
import com.ks.logic.dao.GuildMemberDAO;
import com.ks.logic.dao.GuildSkillDAO;
import com.ks.logic.dao.MailDAO;
import com.ks.logic.dao.MartialWayDAO;
import com.ks.logic.dao.SysMailDAO;
import com.ks.logic.dao.UserAchieveDAO;
import com.ks.logic.dao.UserBuffDAO;
import com.ks.logic.dao.UserDAO;
import com.ks.logic.dao.UserEquipmentDAO;
import com.ks.logic.dao.UserEternalDAO;
import com.ks.logic.dao.UserGuideStepDAO;
import com.ks.logic.dao.UserHeroDAO;
import com.ks.logic.dao.UserPropDAO;
import com.ks.logic.dao.UserStatDAO;
import com.ks.logic.dao.UserTaskDAO;
import com.ks.logic.dao.UserTeamDAO;
import com.ks.logic.dao.UserZoneDAO;
import com.ks.logic.dao.cfg.AchieveDAO;
import com.ks.logic.dao.cfg.ActivityDAO;
import com.ks.logic.dao.cfg.ActivityZoneDAO;
import com.ks.logic.dao.cfg.ArenaCfgDAO;
import com.ks.logic.dao.cfg.CommonRewardDAO;
import com.ks.logic.dao.cfg.ConstantDAO;
import com.ks.logic.dao.cfg.EquipmentDAO;
import com.ks.logic.dao.cfg.EternalDAO;
import com.ks.logic.dao.cfg.ExploreSettingDAO;
import com.ks.logic.dao.cfg.FameDAO;
import com.ks.logic.dao.cfg.GuildRankAwardDao;
import com.ks.logic.dao.cfg.HeroBreakDao;
import com.ks.logic.dao.cfg.HeroDAO;
import com.ks.logic.dao.cfg.MallDAO;
import com.ks.logic.dao.cfg.MartialWayAwardDao;
import com.ks.logic.dao.cfg.MonsterDAO;
import com.ks.logic.dao.cfg.PropDAO;
import com.ks.logic.dao.cfg.SigninDAO;
import com.ks.logic.dao.cfg.SkillDAO;
import com.ks.logic.dao.cfg.TaskBaseSettingDAO;
import com.ks.logic.dao.cfg.UserRuleDAO;
import com.ks.logic.dao.cfg.VIPDAO;
import com.ks.logic.dao.cfg.ZoneDAO;
import com.ks.logic.service.impl.ActivityServiceImpl;
import com.ks.logic.service.impl.ArenaServiceImpl;
import com.ks.logic.service.impl.CommonRewardServiceImpl;
import com.ks.logic.service.impl.ConditionServiceImpl;
import com.ks.logic.service.impl.DataServiceImpl;
import com.ks.logic.service.impl.EffectServiceImpl;
import com.ks.logic.service.impl.FightServiceImpl;
import com.ks.logic.service.impl.GameLoggerServiceImpl;
import com.ks.logic.service.impl.GuildServiceImpl;
import com.ks.logic.service.impl.HeroBreakServiceImpl;
import com.ks.logic.service.impl.HeroServiceImpl;
import com.ks.logic.service.impl.MailServiceImpl;
import com.ks.logic.service.impl.MallServiceImpl;
import com.ks.logic.service.impl.MartialWayServiceImpl;
import com.ks.logic.service.impl.MonsterServiceImpl;
import com.ks.logic.service.impl.PrepareMethodServiceImpl;
import com.ks.logic.service.impl.PrivilegeServiceImpl;
import com.ks.logic.service.impl.PropServiceImpl;
import com.ks.logic.service.impl.SkillServiceImpl;
import com.ks.logic.service.impl.UserAchieveServiceImpl;
import com.ks.logic.service.impl.UserBuffServiceImpl;
import com.ks.logic.service.impl.UserEquipmentServiceImpl;
import com.ks.logic.service.impl.UserEternalServiceImpl;
import com.ks.logic.service.impl.UserHeroServiceImpl;
import com.ks.logic.service.impl.UserIncomeServiceImpl;
import com.ks.logic.service.impl.UserPropServiceImpl;
import com.ks.logic.service.impl.UserServiceImpl;
import com.ks.logic.service.impl.UserTeamServiceImpl;
import com.ks.logic.service.impl.UserZoneServiceImpl;
import com.ks.logic.service.impl.VIPServiceImpl;
import com.ks.logic.service.impl.ZoneServiceImpl;
/**
 * 
 * @author ks
 *
 */
public abstract class BaseService {
	//dao
	protected static final UserDAO userDAO = new UserDAO();
	protected static final GameLoggerDAO gameLoggerDAO = new GameLoggerDAO();
	protected static final HeroDAO heroDAO = new HeroDAO();
	protected static final UserHeroDAO userHeroDAO = new UserHeroDAO();
	protected static final MonsterDAO monsterDAO = new MonsterDAO();
	protected static final FightDAO fightDAO = new FightDAO();
	protected static final UserTeamDAO userTeamDAO = new UserTeamDAO();
	protected static final UserRuleDAO userRuleDAO = new UserRuleDAO();
	protected static final ZoneDAO zoneDAO = new ZoneDAO();
	protected static final UserZoneDAO userZoneDAO = new UserZoneDAO();
	protected static final SkillDAO skillDAO = new SkillDAO();
	protected static final MailDAO mailDAO = new MailDAO();
	protected static final ArenaDAO arenaDAO = new ArenaDAO();
	protected static final ArenaCfgDAO arenaCfgDAO = new ArenaCfgDAO();
	protected static final AreaConfigDAO areaConfigDAO = new AreaConfigDAO();
	protected static final UserStatDAO userStatDAO = new UserStatDAO();
	protected static final GuildDAO guildDAO = new GuildDAO();
	protected static final GuildRankAwardDao guildRankRewardDAO = new GuildRankAwardDao();
	protected static final GuildMemberDAO guildMemberDAO = new GuildMemberDAO();
	protected static final GuildSkillDAO guildSkillDAO = new GuildSkillDAO();
	protected static final GuildApplyDAO guildApplyDAO = new GuildApplyDAO();
	protected static final GuildAccuseDAO guildAccuseDAO = new GuildAccuseDAO();
	protected static final UserPropDAO userPropDAO = new UserPropDAO();
	protected static final PropDAO propDAO = new PropDAO();
	protected static final UserBuffDAO userBuffDAO = new UserBuffDAO();
	protected static final MallDAO mallDAO = new MallDAO();
//	protected static final UserHeroMapDAO userHeroMapDAO = new UserHeroMapDAO();
	protected static final ExploreDAO exploreDAO = new ExploreDAO();
	protected static final ExploreSettingDAO exploreSettingDao = new ExploreSettingDAO();
	protected static final AchieveDAO achieveDAO = new AchieveDAO();
	protected static final UserAchieveDAO userAchieveDAO = new UserAchieveDAO();
	protected static final FriendDAO friendDAO = new FriendDAO();
	protected static final AgainstRequstDAO againstRequstDAO = new AgainstRequstDAO();
	protected static final VIPDAO vipDAO = new VIPDAO();
	protected static final ActivityZoneDAO activityZoneDAO = new ActivityZoneDAO();
	protected static final EquipmentDAO equipmentDAO = new EquipmentDAO();
	protected static final UserEquipmentDAO userEquipmentDAO = new UserEquipmentDAO();
	protected static final EternalDAO eternalDAO = new EternalDAO();
	protected static final UserEternalDAO userEternalDAO = new UserEternalDAO();
	protected static final  MartialWayDAO martialWayDAO = new MartialWayDAO();
	protected static final  MartialWayAwardDao martialWayAwardDAO = new MartialWayAwardDao();
	protected static final  SigninDAO signinDAO = new SigninDAO();
	protected static final  TaskBaseSettingDAO taskBaseSettingDao = new TaskBaseSettingDAO();
//	protected static final  UserDailyTaskDAO userDailyTaskDao = new UserDailyTaskDAO();
//	protected static final  UserRenownTaskDao userRenownTaskDao = new UserRenownTaskDao();
	protected static final  UserTaskDAO userTaskDAO = new UserTaskDAO();
	protected static final  FameDAO fameDAO = new FameDAO();
	protected static final  HeroBreakDao heroBreakDao = new HeroBreakDao();
	/**系统邮件*/
	protected static final SysMailDAO sysMailDao = new SysMailDAO();
	/**活动*/
	protected static final ActivityDAO activityDao = new ActivityDAO();
	/**通用奖励*/
	protected static final CommonRewardDAO commonRewardDao = new CommonRewardDAO();
	/**常数*/
	protected static final ConstantDAO constantDao = new ConstantDAO();
	/**玩家引导*/
	protected static final UserGuideStepDAO userGuideStepDao = new UserGuideStepDAO();
	//service
	protected static final ArenaService arenaService = new ArenaServiceImpl();
	protected static final FightService fightService = new FightServiceImpl();
	protected static final GameLoggerService gameLoggerService = new GameLoggerServiceImpl();
	protected static final GuildService guildService = new GuildServiceImpl();
	protected static final HeroService heroService = new HeroServiceImpl();
	protected static final MailService mailService = new MailServiceImpl();
	protected static final MonsterService monsterService = new MonsterServiceImpl();
	protected static final PropService propService = new PropServiceImpl();
	protected static final SkillService skillService = new SkillServiceImpl();
	protected static final UserBuffService userBuffService = new UserBuffServiceImpl();
	protected static final UserHeroService userHeroService = new UserHeroServiceImpl();
	protected static final UserPropService userPropService = new UserPropServiceImpl();
	protected static final UserService userService = new UserServiceImpl();
	protected static final UserTeamService userTeamService = new UserTeamServiceImpl();
	protected static final UserZoneService userZoneService = new UserZoneServiceImpl();
	protected static final ZoneService zoneService = new ZoneServiceImpl();
	protected static final UserAchieveService userAchieveService = new UserAchieveServiceImpl();
	protected static final UserEquipmentService userEquipmentService = new UserEquipmentServiceImpl();
	protected static final MartialWayService martialWayService = new MartialWayServiceImpl();
	protected static final UserEternalService userEternalService = new UserEternalServiceImpl();
	protected static final MallService mallService = new MallServiceImpl();
	protected static final PrepareMethodService prepareMethodService = new PrepareMethodServiceImpl();
	protected static final HeroBreakService heroBreakService = new HeroBreakServiceImpl();
	protected static final UserIncomeService incomeService = new UserIncomeServiceImpl();
	protected static final PrivilegeService privilegeService = new PrivilegeServiceImpl();
	protected static final VIPService vipService = new VIPServiceImpl();
	protected static final ActivityService activityService = new ActivityServiceImpl();
	protected static final ConditionService conditionService = new ConditionServiceImpl();
	protected static final CommonRewardService commonRewardService = new CommonRewardServiceImpl();
	protected static final EffectService effectService = new EffectServiceImpl();
	protected static final DataService dataService = new DataServiceImpl();
	
}
